Repository cal-itp/data-infra, pull requests merged in 2021-12, with the labels that each got.

#821 feature(payments): Add ID dupe order for each ID in funding sources
  airflow/dags/payments_views_staging/stg_enriched_customer_funding_source.sql
Labels: project-payments

#823 Remove failing device transaction data test in payments pipeline
  airflow/dags/payments_views/payments_rides.sql
  airflow/dags/payments_views_staging/validate_cleaned_device_transaction_pairs_common_fields.sql
Labels: project-payments

#808 Worked examples in warehouse tutorial
  docs/analytics_examples/.gitignore
  docs/analytics_examples/assets/count_trip_stops.png
  docs/analytics_examples/assets/days_until_agency_feed_expires.png
  docs/analytics_examples/assets/distinct_stops_in_trip_stops.png
  docs/analytics_examples/assets/distinct_trips_in_trip_stops.png
  docs/analytics_examples/assets/max_stops_per_trip_by_agency.png
  docs/analytics_examples/assets/most_stops_per_trip_by_agency.png
  docs/analytics_examples/assets/routes_agency_over_time.png
  docs/analytics_examples/assets/stops_agency_over_time.png
  docs/analytics_examples/warehouse_tutorial.md
  docs/analytics_onboarding/overview.md
  docs/analytics_tools/python_libraries.md
  docs/analytics_welcome/about_our_team.md
  docs/analytics_welcome/how_we_work.md
  docs/analytics_welcome/overview.md
  docs/analytics_welcome/what_is_calitp.md
Labels: documentation

#831 Updated docs information for new hires re meetings, slack channels
  docs/analytics_examples/warehouse_tutorial.md
  docs/analytics_onboarding/overview.md
  docs/analytics_tools/overview.md
  docs/analytics_tools/saving_code.md
  docs/analytics_welcome/how_we_work.md
  docs/analytics_welcome/overview.md
Labels: documentation

#839 Reconciling Holly's 'saving_code' branch with PR #831
  docs/analytics_tools/saving_code.md
  docs/analytics_welcome/how_we_work.md
Labels: documentation

#806 WIP (docs): add max_bytes, analytics examples
  airflow/requirements.txt
  docs/_config.yml
  docs/_toc.yml
  docs/analytics_examples/new_tutorial.md
  docs/analytics_tools/data_catalogs.md
  docs/analytics_tools/notebooks.md
Labels: documentation

#853 Add Tuolumne gtfs entry to agencies.yml
  airflow/data/agencies.yml
Labels: airflow

#862 Docs: close out analytics_tools/notebooks
  docs/analytics_tools/assets/step-1-gh-drag-drop.png
  docs/analytics_tools/assets/step-2-gh-drag-drop.png
  docs/analytics_tools/notebooks.md
  docs/analytics_tools/saving_code.md
  docs/analytics_tools/storing_data.md
  docs/warehouse/views.md
Labels: documentation

#869 Docs: close out analytics_tools/python_libraries
  docs/analytics_tools/python_libraries.md
Labels: documentation

#881 (docs): saving code, add more GitHub commands
  docs/analytics_tools/saving_code.md
Labels: documentation

#874 Add customer and funding source info to payments_rides view
  airflow/dags/payments_views/payments_rides.sql
  airflow/dags/payments_views_staging/stg_cleaned_customer_funding_source_vaults.sql
  airflow/dags/payments_views_staging/stg_cleaned_customers.sql
  airflow/dags/payments_views_staging/validate_cleaned_micropayment_transaction_time_order.sql
  airflow/dags/payments_views_staging/validate_cleaned_principal_customer_ids.sql
Labels: project-payments

#892 Update new-team-member.md
  .github/ISSUE_TEMPLATE/new-team-member.md
Labels: new team member

#802 WIP: Document tables in Airtable Transit Database
  docs/datasets_and_tables/transitdatabase.md
Labels: documentation
