Repository cal-itp/data-infra, pull requests merged in 2021-11, with the labels that each got.

#678 Docs: add Google ID
  docs/_config.yml
Labels: documentation

#676 Docs: update author to Cal-ITP
  docs/_config.yml
Labels: documentation

#700 Onboarding chapter
  docs/_toc.yml
  docs/analytics_onboarding/01_technical_onboarding.md
  docs/analytics_onboarding/overview.md
  docs/analytics_publishing/01_how_to_publish.md
  docs/analytics_tools/01_tools_quick_links.md
  docs/analytics_tools/02_querying.md
  docs/analytics_tools/03_bi_dashboards.md
  docs/analytics_tools/04_notebooks.md
  docs/analytics_tools/05_python_libraries.md
  docs/analytics_tools/06_saving_code.md
  docs/analytics_tools/07_storing_data.md
  docs/analytics_tools/overview.md
  docs/analytics_welcome/01_what_is_calitp.md
  docs/analytics_welcome/03_how_we_work.md
  docs/analytics_welcome/overview.md
  docs/intro.md
Labels: documentation, epic

#710 fix(docs): pulled explainer sentance to below admonition, experimente…
  docs/analytics_onboarding/overview.md
Labels: documentation

#714 'How to Open Issues' screencast
  docs/analytics_onboarding/overview.md
  docs/analytics_welcome/03_how_we_work.md
Labels: documentation

#713 feature(payments): Add field descriptions for payments_rides view
  airflow/dags/payments_views/payments_rides.sql
Labels: project-payments

#750 Technical onboarding tweaks
  docs/analytics_onboarding/overview.md
  docs/analytics_welcome/03_how_we_work.md
Labels: documentation

#755 fix(payments): Escape regex parameters in formatted string
  airflow/dags/dags.py
Labels: project-payments

#760 fix(docs): easy doc fixes
  docs/_toc.yml
  docs/analytics_examples/sample-catalog-viewer.md
  docs/analytics_examples/sample-catalog.yml
  docs/analytics_onboarding/overview.md
  docs/analytics_tools/01_tools_quick_links.md
  docs/analytics_tools/02_querying.md
  docs/analytics_tools/overview.md
  docs/warehouse/02_sql_snippets.md
Labels: documentation

#764 Docs - Analytics tools overview section
  docs/analytics_publishing/overview.md
  docs/analytics_tools/03_bi_dashboards.md
  docs/analytics_tools/04_notebooks.md
  docs/analytics_tools/05_python_libraries.md
  docs/analytics_tools/06_saving_code.md
  docs/analytics_tools/07_storing_data.md
  docs/analytics_tools/08_data_catalogs.md
  docs/analytics_tools/overview.md
  docs/analytics_welcome/overview.md
  docs/datasets_and_tables/01_overview.md
  docs/warehouse/overview.md
Labels: documentation

#768 fix(payments): Add Mjumbe to the failure emails for payments DAGs
  airflow/dags/payments_loader/METADATA.yml
  airflow/dags/payments_views_staging/METADATA.yml
Labels: project-payments

#772 fix(reports): reports index was filtering those without feed info
  airflow/dags/gtfs_views/reports_gtfs_schedule_index.sql
Labels: reports-website

#767 Restructuring and repairing the warehouse tutorial
  docs/_toc.yml
  docs/airflow/overview.md
  docs/analytics_examples/01_analysis_examples.md
  docs/analytics_examples/01_warehouse_tutorial.md
  docs/analytics_examples/overview.md
  docs/analytics_tools/03_bi_dashboards.md
  docs/analytics_tools/04_notebooks.md
  docs/analytics_tools/06_saving_code.md
  docs/analytics_tools/overview.md
  docs/analytics_welcome/overview.md
  docs/data_consumers/overview.md
  docs/intro.md
  docs/project_leads/overview.md
Labels: documentation
