Repository cal-itp/data-infra, pull requests merged in 2022-01, with the labels that each got.

#911 Update gtfs feeds now hosted by LACMTA
  airflow/data/agencies.yml
Labels: airflow

#883 Misc Docs Fixes - Review Findings
  docs/analytics_publishing/how_to_publish.md
  docs/analytics_tools/notebooks.md
  docs/analytics_tools/overview.md
  docs/analytics_tools/python_libraries.md
  docs/analytics_tools/saving_code.md
  docs/analytics_welcome/how_we_work.md
Labels: documentation

#897 Fix broken code cells in python_libraries
  docs/_config.yml
  docs/analytics_tools/python_libraries.md
Labels: documentation

#941 Misc Docs Updates - adding lunchnlearn recordings, adding function to python libraries
  docs/analytics_tools/python_libraries.md
  docs/analytics_welcome/how_we_work.md
Labels: documentation

#947 Update version of jupterhub image running on k8s cluster
  kubernetes/apps/charts/jupyterhub/values.yaml
Labels: enhancement

#975 fix(airflow): rename airtable related items
  airflow/dags/sandbox/airtable_denormalized.sql
  airflow/dags/sandbox/load_airtable_child.yml
  airflow/dags/sandbox/op_airtable_to_warehouse.yml
  airflow/docker-compose.yaml
  airflow/requirements.txt
  docs/warehouse/views.md
Labels: airtable

#990 feat(airtable): load california transit base data to warehouse
  airflow/dags/airtable_loader/METADATA.yml
  airflow/dags/airtable_loader/california_transit_county_geography.yml
  airflow/dags/airtable_loader/california_transit_eligibility_programs.yml
  airflow/dags/airtable_loader/california_transit_fare_systems.yml
  airflow/dags/airtable_loader/california_transit_funding_programs.yml
  airflow/dags/airtable_loader/california_transit_gtfs_datasets.yml
  airflow/dags/airtable_loader/california_transit_gtfs_service_data.yml
  airflow/dags/airtable_loader/california_transit_ntd_agency_info.yml
  airflow/dags/airtable_loader/california_transit_organizations.yml
  airflow/dags/airtable_loader/california_transit_place_geography.yml
  airflow/dags/airtable_loader/california_transit_rider_requirements.yml
  airflow/dags/airtable_loader/california_transit_service_component.yml
  airflow/dags/airtable_loader/california_transit_services.yml
Labels: airtable

#1007 chore(docs): Moving DAG maintenance information
  docs/_toc.yml
  docs/airflow/dags-maintenance.md
  docs/datasets_and_tables/gtfs_rt.md
  docs/datasets_and_tables/gtfs_schedule.md
  docs/datasets_and_tables/mst_payments.md
  docs/datasets_and_tables/transitdatabase.md
  docs/datasets_and_tables/views.md
Labels: documentation, infrastructure
