Repository cal-itp/data-infra, pull requests merged in 2022-02, with the labels that each got.

#999 Refactor GTFS-RT Archiver for reliability and tracing
  .github/workflows/push_to_gcloud.yml
  .pre-commit-config.yaml
  docs/services/gtfs-rt-archive.md
  docs/services/gtfs-rt-archive.mmd
  kubernetes/apps/overlays/gtfs-rt-archive-release/kustomization.yaml
  services/gtfs-rt-archive/.gitignore
  services/gtfs-rt-archive/Dockerfile
  services/gtfs-rt-archive/docker-compose.yml
  services/gtfs-rt-archive/gtfs-rt-archive.py
  services/gtfs-rt-archive/src/gtfs_rt_archive/__init__.py
  services/gtfs-rt-archive/src/gtfs_rt_archive/__main__.py
  services/gtfs-rt-archive/src/gtfs_rt_archive/eventbus.py
  services/gtfs-rt-archive/src/gtfs_rt_archive/mapperfns.py
  services/gtfs-rt-archive/src/gtfs_rt_archive/threadpool.py
  services/gtfs-rt-archive/src/gtfs_rt_archive/threads/__init__.py
  services/gtfs-rt-archive/src/gtfs_rt_archive/threads/fetcher.py
  services/gtfs-rt-archive/src/gtfs_rt_archive/threads/mappers.py
  services/gtfs-rt-archive/src/gtfs_rt_archive/threads/ticker.py
  services/gtfs-rt-archive/src/gtfs_rt_archive/threads/writer.py
  services/gtfs-rt-archive/src/setup.py
Labels: P0

#986 Docs: Closing out 'Contribute to the Docs' Section
  docs/_toc.yml
  docs/analytics_examples/warehouse_tutorial.md
  docs/contribute/assets/commit-screenshot.png
  docs/contribute/assets/gh-action.png
  docs/contribute/assets/netlify-link.png
  docs/contribute/assets/pr-intro.png
  docs/contribute/assets/suggest-edit.png
  docs/contribute/content_types.md
  docs/contribute/contribute-best-practices.md
  docs/contribute/overview.md
  docs/contribute/submitting_changes.md
  docs/data_consumers/overview.md
  docs/intro.md
  docs/project_leads/overview.md
Labels: documentation

#1056 fix(gtfs-rt): define json schema for vehicle positions external table
  airflow/dags/rt_loader/external_service_alerts.sql
  airflow/dags/rt_loader/external_trip_updates.sql
  airflow/dags/rt_loader/external_vehicle_positions.sql
Labels: gtfs-realtime

#1057 docs(airflow): adding how to check the logs of PodOperators
  docs/_toc.yml
  docs/airflow/local-setup.md
  docs/analytics_onboarding/overview.md
Labels: documentation

#1061 fix(gtfs-rt): fix data types for vehicle positions external table schema
  airflow/dags/rt_loader/external_vehicle_positions.sql
Labels: gtfs-realtime

#1070 fix(gtfs-schedule): fix foothill transit static url
  airflow/data/agencies.yml
Labels: project-gtfs-schedule

#1041 docs(Airtable): Update Transit Database Documentation
  docs/datasets_and_tables/transitdatabase.md
Labels: documentation, airtable

#902 Validate an hour of data across all feeds
  airflow/README.md
  airflow/dags/gtfs_loader/calitp_feed_latest.sql
  airflow/dags/gtfs_loader/calitp_feed_status.sql
  airflow/dags/gtfs_loader/gtfs_schedule_tables_load.py
  airflow/dags/rt_loader/create_validation_params.py
  airflow/dags/rt_loader/external_calitp_validation_params.sql
  airflow/dags/rt_loader/load_rt_validations.yml
  airflow/dags/sandbox/op_pod_operator.yml
Labels: gtfs-realtime, P1

#1099 fix(gtfs schedule): remove duplicate feed_info entries
  airflow/dags/gtfs_views_staging/feed_info_clean.sql
Labels: project-gtfs-schedule

#1106 feat(gtfs-rt): add calitp files to views
  airflow/dags/rt_loader_files/calitp_files_process.py
  airflow/dags/rt_loader_files/external_calitp_files.sql
  airflow/dags/rt_loader_files/rt_views_gtfs_rt_fact_files.sql
  script/requirements.txt
Labels: gtfs-realtime

#1108 feat(gtfs-rt): wide hourly view of calitp files
  airflow/dags/rt_loader_files/rt_views_gtfs_rt_fact_files_wide_hourly.sql
Labels: gtfs-realtime

#1109 feat(gtfs-rt): create fact_daily_feeds
  airflow/dags/rt_views/gtfs_rt_fact_daily_feeds.sql
Labels: gtfs-realtime

#1082 fix(airtable): add dummy airtable loader for external dependencies
  airflow/dags/airtable_views/california_transit_gtfs_datasets.sql
  airflow/dags/airtable_views/california_transit_gtfs_service_data.sql
  airflow/dags/airtable_views/california_transit_map_gtfs_datasets_aggregated_to_x_self.sql
  airflow/dags/airtable_views/california_transit_map_gtfs_datasets_dataset_producers_x_organizations_gtfs_datasets_produced.sql
  airflow/dags/airtable_views/california_transit_map_gtfs_datasets_dataset_publisher_x_organizations_gtfs_datasets.sql
  airflow/dags/airtable_views/california_transit_map_gtfs_datasets_gtfs_service_mapping_x_gtfs_service_data_gtfs_dataset.sql
  airflow/dags/airtable_views/california_transit_map_gtfs_service_data_reference_static_gtfs_service_x_self.sql
  airflow/dags/airtable_views/california_transit_map_organizations_mobility_services_managed_x_services_provider.sql
  airflow/dags/airtable_views/california_transit_map_organizations_mobility_services_operated_x_services_operator.sql
  airflow/dags/airtable_views/california_transit_map_organizations_parent_organization_x_self.sql
  airflow/dags/airtable_views/california_transit_map_services_gtfs_services_association_x_gtfs_service_data_services.sql
  airflow/dags/airtable_views/california_transit_map_services_paratransit_for_x_self.sql
  airflow/dags/airtable_views/california_transit_organizations.sql
  airflow/dags/airtable_views/california_transit_services.sql
  airflow/dags/airtable_views/dummy_airtable_loader.yml
Labels: airtable

#1113 fix(gtfs-rt): fix external dependency reference
  airflow/dags/rt_views/gtfs_rt_fact_daily_feeds.sql
Labels: gtfs-realtime

#1119 Fix gtfs rt define schemas for trip updates & service alerts
  airflow/dags/rt_loader/external_service_alerts.sql
  airflow/dags/rt_loader/external_trip_updates.sql
Labels: gtfs-realtime

#1115 fix(payments): Correct cardinality for micropayments:transactions
  airflow/dags/payments_views/payments_rides.sql
  airflow/dags/payments_views/sbmtd_transactions.sql
  airflow/dags/payments_views_staging/stg_cleaned_micropayment_device_transactions.sql
  airflow/dags/payments_views_staging/stg_cleaned_micropayments.sql
  airflow/dags/payments_views_staging/validate_cleaned_micropayment_device_transactions.sql
Labels: project-payments

#1114 Feat gtfs rt daily file total
  airflow/dags/rt_loader_files/calitp_files_process.py
  airflow/dags/rt_loader_files/rt_views_gtfs_rt_fact_files_wide_hourly.sql
Labels: gtfs-realtime

#1127 fix(agencies.yaml): correct sacrt rt urls
  airflow/data/agencies.yml
Labels: gtfs-realtime

#1135 fix(gtfs-rt): expand globbing window so we get all files in calitp_files
  airflow/dags/rt_loader_files/calitp_files_process.py
Labels: gtfs-realtime

#1121 feat(amplitude-ingest): Amplitude API export
  airflow/plugins/operators/amplitude_to_flattened_json.py
Labels: project-benefits
